version: "3.8"
services:
  php:
    build:
      context: docker/dockerfiles
      dockerfile: php.Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}"
      - "${NGINX_SSL_HOST_PORT}:${NGINX_SSL_CONTAINER_PORT}"
    volumes:
      - ./:/app
      - ./docker/nginx/ssl:/etc/ssl
      - ./docker/nginx/snippets:/etc/nginx/snippets
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php
      - db
  db:
    build:
      context: docker/dockerfiles
      dockerfile: pgsql.Dockerfile
    working_dir: /var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 5
    restart: always
    ports:
      - "${DB_EXPOSE_PORT}:${DB_PORT}"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - TZ=$TZ
      - PGTZ=$PGTZ

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./composer.json:/app/composer.json:ro
      - ./composer.lock:/app/composer.lock:ro
      - ./vendor:/app/vendor
    command: install --ignore-platform-reqs --no-interaction --no-scripts --prefer-dist
